In [28]:
import pandas as pd 
import numpy as np
from sklearn.linear_model import LinearRegression

In [29]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend' , 'Administration' , 'Marketing Spend' , 'Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

,R&D Spend,Administration,Marketing Spend,Profit
21,8.0,15.0,30.0,11.0
37,4.0,5.0,20.0,9.0
2,15.0,10.0,41.0,19.0
14,12.0,16.0,26.0,13.0
44,2.0,15.0,3.0,7.0


In [30]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-2] = np.nan
df

,R&D Spend,Administration,Marketing Spend,Profit
21,8.0,15.0,30.0,11.0
37,NaN,5.0,20.0,9.0
2,15.0,10.0,41.0,19.0
14,12.0,NaN,26.0,13.0
44,2.0,15.0,NaN,7.0


In [31]:
# Step - 1 Impute all missing values with mean of respective sol
df0 = pd.DataFrame()
df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())


In [32]:
df0

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,9.25,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.25,26.00
44,2.00,15.00,29.25


In [33]:
# remove the column 1 imputed value
df1 = pd.DataFrame()
df1 = df0.copy()
df1.iloc[1,0] = np.nan

In [34]:
# use first 3 rows to build  a model and use the last for prediction
x = df1.iloc[[0,2,3,4],1:3]
x

,Administration,Marketing Spend
21,15.00,30.00
2,10.00,41.00
14,11.25,26.00
44,15.00,29.25


In [35]:
y = df1.iloc[[0,2,3,4] , 1:3]
y

,Administration,Marketing Spend
21,15.00,30.00
2,10.00,41.00
14,11.25,26.00
44,15.00,29.25


In [36]:
lr = LinearRegression()
lr.fit(x,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

c:\Users\Arjun Kaushik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[ 5., 20.]])

In [37]:
df1.iloc[1,0] = 5.

In [38]:
df1

,R&D Spend,Administration,Marketing Spend
21,8.0,15.00,30.00
37,5.0,5.00,20.00
2,15.0,10.00,41.00
14,12.0,11.25,26.00
44,2.0,15.00,29.25


In [39]:
#Remove the column 2 imputed value 
df1.iloc[3,1] = np.nan
df1

,R&D Spend,Administration,Marketing Spend
21,8.0,15.0,30.00
37,5.0,5.0,20.00
2,15.0,10.0,41.00
14,12.0,NaN,26.00
44,2.0,15.0,29.25


In [40]:
x = df1.iloc[[0,2,3,4] , [0,2]]
x

,R&D Spend,Marketing Spend
21,8.0,30.00
2,15.0,41.00
14,12.0,26.00
44,2.0,29.25


In [41]:
y = df1.iloc[[0,1,2,4] , 1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [42]:
lr.fit(x,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

c:\Users\Arjun Kaushik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.99236091])

In [43]:
df1.iloc[3,1] = 10.9

In [44]:
df1

,R&D Spend,Administration,Marketing Spend
21,8.0,15.0,30.00
37,5.0,5.0,20.00
2,15.0,10.0,41.00
14,12.0,10.9,26.00
44,2.0,15.0,29.25


In [47]:
df1.iloc[-1,-1] = np.nan

In [48]:
df1

,R&D Spend,Administration,Marketing Spend
21,8.0,15.0,30.0
37,5.0,5.0,20.0
2,15.0,10.0,41.0
14,12.0,10.9,26.0
44,2.0,15.0,NaN


In [51]:
x = df1.iloc[0:4 , 0:2]
x

,R&D Spend,Administration
21,8.0,15.0
37,5.0,5.0
2,15.0,10.0
14,12.0,10.9


In [52]:
y = df1.iloc[[0,1,2,3] , -1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [53]:
lr.fit(x,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

c:\Users\Arjun Kaushik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([18.81332042])

In [57]:
df1.iloc[-1,-1] = 18.81

In [59]:
# After 1st Iteration 
df1

,R&D Spend,Administration,Marketing Spend
21,8.0,15.0,30.00
37,5.0,5.0,20.00
2,15.0,10.0,41.00
14,12.0,10.9,26.00
44,2.0,15.0,18.81


In [ ]:
# Subtract 0th iteration from 1st iteration
df0 - df1
# After this comtine the following steps until the difference will be 0 so we got an accurate value of the missing  value.

,R&D Spend,Administration,Marketing Spend
21,0.00,0.00,0.00
37,4.25,0.00,0.00
2,0.00,0.00,0.00
14,0.00,0.35,0.00
44,0.00,0.00,10.44
